image: nexus3.lan.itkweb.fr:5000/itk/ci-sciconda

stages:
  - test
  - deploy

before_script:
  - source activate ci
  - pip install pyci
  - pyci install

pages:
  stage: deploy
  only:
  - develop
  script:
  - pyci doc
  - mv build/sphinx/html public
  artifacts:
    paths:
    - public

ci:test:
  stage: test
  script:
    - pyci test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)\s*$/'

ci:deploy:
  stage: deploy
  only:
    - tags
  script:
    - pyci check_tags
    - pyci write_changelog
    - pyci package
    - pyci publish
