# {# pkglts, conda.package
package:
  name: oapkg
  version: "0.1.0"
# #}

# {# pkglts, conda.src
source:
  path:
    ../
# #}

requirements:
  build:
    - python
    - setuptools

  run:
    - python

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

# {# pkglts, conda.about
about:
  summary: "Default template for openalea packages."
  license: "CeCILL-C"
  license_file: LICENSE
# #}
